spring:
  application:
    name: data-multidatasource
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://192.168.5.128:5432/postgres
    username: postgres
    password: AsdfAsdf_123
  second-datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://192.168.5.128:5432/mlogdb?useUnicode=true&characterEncoding=utf8&currentSchema=public
    username: postgres
    password: AsdfAsdf_123
  third-datasource:
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    jdbc-url: jdbc:hive2://10.254.222.201:10000/hive_jdbc_test
    username: root
    password: